#Requires -Version 5.1
<#
.SYNOPSIS
  Install milestone M2 mods (USSEP, Alternate Start) from mo2/downloads into mo2/mods.
.NOTES
  Edits modlist/plugins -- refuse if MO2 is running unless -RestartMo2 (ADR 0013).
  Places mods under separators by category (ADR 0014). USSEP is LAL's declared dep (ADR 0015).
#>
[CmdletBinding()]
param(
  [string]$Milestone = 'M2',
  [switch]$RestartMo2
)

$ErrorActionPreference = 'Stop'
$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
. (Join-Path $PSScriptRoot 'lib\Ebonveil.Nexus.ps1')
. (Join-Path $PSScriptRoot 'lib\Ebonveil.Mo2.ps1')

$Mo2 = Join-Path $RepoRoot 'mo2'
$Downloads = Join-Path $Mo2 'downloads'
$Mods = Join-Path $Mo2 'mods'
$ProfileDir = Join-Path $Mo2 'profiles\Default'
$ResolvedPath = Join-Path $Downloads '.ebonveil-resolved.json'
$ManifestPath = Join-Path $RepoRoot 'manifest\mods.json'
$seven = Find-7Zip
$utf8NoBom = New-Object System.Text.UTF8Encoding $false

$manifest = Get-Content $ManifestPath -Raw | ConvertFrom-Json
$resolved = $null
if (Test-Path -LiteralPath $ResolvedPath) {
  $resolved = Get-Content -LiteralPath $ResolvedPath -Raw | ConvertFrom-Json
}

function Get-ArchiveForMod {
  param([string]$ModKey, [int]$ModId)
  if ($resolved -and $resolved.$ModKey -and $resolved.$ModKey.fileName) {
    $p = Join-Path $Downloads $resolved.$ModKey.fileName
    if (Test-Path -LiteralPath $p) { return Get-Item -LiteralPath $p }
  }
  $hit = Find-DownloadByModId -DownloadsDir $Downloads -ModId $ModId
  if (-not $hit) { throw "No download for $ModKey (modId $ModId). Run: pwsh -File tools/restore-mods.ps1 -Milestone $Milestone" }
  return $hit
}

function Write-MetaIni {
  param(
    [string]$ModDir, [int]$ModId, [string]$Version,
    [string]$InstallationFile, [string]$Url, [int]$FileId = 0
  )
  $lines = @(
    '[General]'
    'gameName=SkyrimSE'
    "modid=$ModId"
    "version=$Version"
    'newestVersion='
    'category=0'
    "installationFile=$InstallationFile"
    'repository=Nexus'
    "url=$Url"
    "nexusUrl=$Url"
    'ignoredVersion='
    ''
    '[installedFiles]'
    "1\modid=$ModId"
    "1\fileid=$FileId"
    'size=1'
  )
  [System.IO.File]::WriteAllLines((Join-Path $ModDir 'meta.ini'), $lines, $utf8NoBom)
}

function Install-SimpleMo2Mod {
  param($ModEntry, [string]$FolderName)
  $modId = [int]$ModEntry.nexus.modId
  $archive = Get-ArchiveForMod -ModKey $ModEntry.id -ModId $modId
  $modDir = Join-Path $Mods $FolderName
  if (Test-Path -LiteralPath $modDir) { Remove-Item -LiteralPath $modDir -Recurse -Force }
  New-Item -ItemType Directory -Force -Path $modDir | Out-Null
  & $seven x -y "-o$modDir" $archive.FullName | Out-Null

  # Collapse single nested top folder if the archive wrapped everything
  $kids = @(Get-ChildItem -LiteralPath $modDir -Force | Where-Object { $_.Name -ne 'meta.ini' })
  if ($kids.Count -eq 1 -and $kids[0].PSIsContainer) {
    $inner = $kids[0].FullName
    Get-ChildItem -LiteralPath $inner -Force | ForEach-Object {
      Move-Item -LiteralPath $_.FullName -Destination $modDir -Force
    }
    Remove-Item -LiteralPath $inner -Recurse -Force
  }

  $ver = ''
  $fileId = 0
  $url = [string]$ModEntry.nexus.url
  if ($resolved -and $resolved.($ModEntry.id)) {
    $ver = [string]$resolved.($ModEntry.id).version
    $fileId = [int]$resolved.($ModEntry.id).fileId
    if ($resolved.($ModEntry.id).url) { $url = [string]$resolved.($ModEntry.id).url }
  }
  Write-MetaIni -ModDir $modDir -ModId $modId -Version $ver -InstallationFile $archive.Name -Url $url -FileId $fileId
  Write-Host "Installed $FolderName <- $($archive.Name)"
  return $FolderName
}

function Enable-Plugins {
  param([string[]]$PluginNames)
  $pluginsPath = Join-Path $ProfileDir 'plugins.txt'
  $loPath = Join-Path $ProfileDir 'loadorder.txt'
  $plugins = @()
  if (Test-Path $pluginsPath) {
    $plugins = @(Get-Content $pluginsPath | Where-Object { $_ -notmatch '^# This file was automatically' })
  }
  $lo = @()
  if (Test-Path $loPath) {
    $lo = @(Get-Content $loPath | Where-Object { $_ -notmatch '^# This file was automatically' })
  }

  foreach ($esp in $PluginNames) {
    $plugins = @($plugins | Where-Object { $_ -ne "*$esp" -and $_ -ne $esp -and $_ -ne "-$esp" })
    $plugins += "*$esp"
    $lo = @($lo | Where-Object { $_ -ne $esp })
    $lo += $esp
  }

  $pOut = @('# This file was automatically generated by Mod Organizer / Ebonveil') + $plugins
  $lOut = @('# This file was automatically generated by Mod Organizer / Ebonveil') + $lo
  [System.IO.File]::WriteAllLines($pluginsPath, $pOut, $utf8NoBom)
  [System.IO.File]::WriteAllLines($loPath, $lOut, $utf8NoBom)
  Write-Host "Enabled plugins: $($PluginNames -join ', ')"
}

# --- run ---
$mo2WasRunning = $false
if (Test-Mo2Running) {
  if ($RestartMo2) { $mo2WasRunning = Stop-Mo2 }
  else { Assert-Mo2NotRunning -ScriptHint "./tools/install-m2.ps1 -Milestone $Milestone" }
}

Write-Host "=== Ebonveil install milestone $Milestone ==="
$targets = @($manifest.mods | Where-Object {
    ($_.milestone -eq $Milestone -or $Milestone -eq '*') -and $_.install -eq 'mo2-mod' -and $_.nexus
  })
# Deps first: entries with empty requires, then the rest (LAL after USSEP).
$ordered = [System.Collections.Generic.List[object]]::new()
foreach ($m in $targets) {
  if (-not $m.requires -or @($m.requires).Count -eq 0) { $ordered.Add($m) }
}
foreach ($m in $targets) {
  if ($m.requires -and @($m.requires).Count -gt 0) { $ordered.Add($m) }
}

$placements = @()
$allPlugins = @()
foreach ($mod in $ordered) {
  $folder = if ($mod.id -eq 'ussep') { 'USSEP' }
            elseif ($mod.id -eq 'alternate-start-lal') { 'Alternate Start - Live Another Life' }
            else { [string]$mod.name }
  [void](Install-SimpleMo2Mod -ModEntry $mod -FolderName $folder)
  $cat = if ($mod.category) { [string]$mod.category } else { 'Other Mods' }
  $placements += @{ Name = $folder; Separator = $cat }
  if ($mod.plugins) { $allPlugins += @($mod.plugins) }
}

if ($placements.Count -gt 0) {
  Update-Mo2ModlistPlacements -ProfileDir $ProfileDir -ModsDir $Mods -RepoRoot $RepoRoot -Placements $placements
}
Sync-Mo2ManagedSeparators -ProfileDir $ProfileDir -ModsDir $Mods -RepoRoot $RepoRoot
if ($allPlugins.Count -gt 0) { Enable-Plugins -PluginNames $allPlugins }

Write-Host "=== milestone $Milestone install complete ==="
if ($mo2WasRunning) { Start-Mo2 | Out-Null }
else { Write-Host 'Restart MO2 if open so the new mods appear.' }
